"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Funcionario_1 = require("./models/Funcionario");
var Cliente_1 = require("./models/Cliente");
var Orcamento_1 = require("./models/Orcamento");
var seila = new Funcionario_1.Funcionario("Jonathan", 20, 30);
var seila6 = new Funcionario_1.Funcionario("Marcondes", 400, 1);
var seila8 = new Funcionario_1.Funcionario("Marcondes3", 299, 1);
seila.realizarFechamento();
seila.exibirDetalhes();
var seila2 = new Cliente_1.Cliente("Joaozim", "33213", "Rua Pepino, 32", "Pessoa Fisica");
var orcamento1 = new Orcamento_1.Orcamento(seila2, 4);
orcamento1.adicionarFuncionario(seila6);
orcamento1.adicionarFuncionario(seila8);
orcamento1.adicionarServico("Limpeza de Vidros", 300);
console.log(orcamento1.gastoMaodeObra());
console.log(orcamento1.sugerirValorMinimo());
console.log(orcamento1.totalServicos());
console.log(orcamento1.CalculoGeral());
